##just createing build
# name: React CI - Build Artifactss

# on:
#   push:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20.9.0

#       - name: Install dependencies
#         run: npm install

#       - name: Build React apppp
#         run: CI=false npm run build

#       - name: Upload build artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: react-build
#           path: build/

##createing and deploying build into github pages
# name: React CI/CD - GitHub Pages

# on:
#   push:
#     branches: [ master ]

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   build:
#     name: CI - Build React
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - run: npm install
#       - run: npm test -- --watch=false || true
#       - run:  CI=false npm run build

#       - uses: actions/upload-artifact@v4
#         with:
#           name: react-build
#           path: build/

#   deploy:
#     name: CD - Deploy to GitHub Pages
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           name: react-build
#           path: build

#       - uses: actions/configure-pages@v5
#       - uses: actions/upload-pages-artifact@v3
#         with:
#           path: build
##for deploying to github pages in package.json add "homepage": "https://kjayanthnaik.github.io/RAG_CHATBOT/",
#       - uses: actions/deploy-pages@v4

##building using docker and deploying to render
name: Docker CI - Frontend

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest
